# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  build:
    desc: "Build the application"
    cmds:
    - GOFLAGS=-mod=mod go build -o bin/voting_app internal/main.go
  run: 
    desc: Run the app
    cmds:
    - GOFLAGS=-mod=mod go run internal/main.go
  swagger.gen:
    desc: Generate Go code
    cmds:
    - GOFLAGS=-mod=mod go generate github.com/dunefro/voting_app/internal github.com/dunefro/voting_app/pkg/swagger
  swagger.validate:
      desc: Validate swagger
      cmds:
      - swagger validate pkg/swagger/swagger.yml
  swagger.doc:
      desc: Doc for swagger
      cmds:
      - docker run -i yousan/swagger-yaml-to-html < pkg/swagger/swagger.yml > doc/index.html